### ISSUE TITLE
How do I set an auto dismiss timer?

### ISSUE THREAD

**Issue by Testator** [emre1512/Noty#1]
I want it dismiss itself after a few seconds.. How do I code this. Thanks in advance!

**Comment by emre1512** [comment]
`(...).setAnimation(RevealAnim reveal, DismissAnim dismiss, int revealTime, int dismissTime);`

**Comment by Testator** [comment]
doesn not work?

**Comment by Testator** [comment]
.setAnimation(Noty.RevealAnim.SLIDE_DOWN, Noty.DismissAnim.BACK_TO_TOP, 1000,1000)

is the default.. doesnt do anything
